In [117]:
import numpy as np
import pandas as pd

Створити програму, яка:

1. Генерує випадкові і невипадкові масиви різними способами, зазначеними в теоретичних відомостях.

In [118]:
a = np.arange(1, 9, 2) #від 1 до 9 із кроком 2
print(a)

[1 3 5 7]


In [119]:
b = np.ones((2, 2), dtype='int') #одинички
print(b)

[[1 1]
 [1 1]]


In [120]:
c = np.random.rand(2, 2) #рівномірно розподілені випадкові числа
print(c)

[[0.28482577 0.65120722]
 [0.56176905 0.66921339]]


In [121]:
d = np.random.randint(0, 69, (4, 4)) #випадкові цілі числа
print(d)

[[64  8  5 31]
 [50 67 40 63]
 [61 32 21 38]
 [62  5 16 47]]


In [122]:
e = np.linspace(0, 1, 5) #5 рівномірно розміщених числа від 0 до 1
print(e)

[0.   0.25 0.5  0.75 1.  ]


2. Демонструє звернення до елементів масиву за допомогою індексів, в тому числі від’ємних; виділення підмасивів як одновимірних, так і багатовимірних масивів.

In [123]:
a[0], a[-1]

(1, 7)

In [124]:
d[1, 0]

50

In [125]:
d[1][0]

50

In [126]:
d[1][0:4:3]

array([50, 63])

In [127]:
d[1:3, 1:4:1]

array([[67, 40, 63],
       [32, 21, 38]])

3. Демонструє основні арифметичні операції над масивами, а також роботу методів reduce, accumulate, outer.

In [128]:
a

array([1, 3, 5, 7])

In [129]:
a * 2

array([ 2,  6, 10, 14])

In [130]:
a + 2

array([3, 5, 7, 9])

In [131]:
np.add.accumulate(a)

array([ 1,  4,  9, 16])

In [132]:
np.add.reduce(a)

16

In [133]:
np.multiply.outer(a, a)

array([[ 1,  3,  5,  7],
       [ 3,  9, 15, 21],
       [ 5, 15, 25, 35],
       [ 7, 21, 35, 49]])

4. Вираховує статистичні характеристики, а саме, мінімальне і максимальне значення, вибіркові середнє, дисперсію, середньоквадратичне відхилення, медіану та 25 та 75 персентилі, величини ширина пелюстки (petal_width) з набору даних щодо квіток ірису (iris.csv).

In [134]:
data = pd.read_csv('iris.csv')
petal_width = np.array(data['petal_width'])

In [135]:
data

sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [136]:
np.min(petal_width)

0.1

In [137]:
np.max(petal_width)

2.5

In [138]:
np.mean(petal_width)

1.1986666666666668

In [139]:
np.var(petal_width)

0.5785315555555555

In [140]:
np.std(petal_width)

0.7606126185881716

In [141]:
np.median(petal_width)

1.3

In [142]:
np.percentile(petal_width, 25)

0.3

In [143]:
np.percentile(petal_width, 75)

1.8